config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: "omniauth_callbacks",
      registrations:      "user_registrations"
    }

  authenticate :user do
    resources :users
    match "/users/:id/finish_signup" => "users#finish_signup",
      via: [:get, :patch], :as => :finish_signup
  end

  resources :events do
    get "register/:package_slug" => "registrations#register",
      as: :package_registration
    get "register" => "registrations#register", as: :registration
    post "register" => "registrations#register"

    resources :activities, only: [:index, :new, :create]
    namespace "activities", module: nil, as: nil do
      get    ":type"          => "activities#index", as: :activities_by_type
      get    ":type/new"      => "activities#new",   as: :new_activity_by_type
      post   ":type"          => "activities#create"
      get    ":type/:id"      => "activities#show",  as: :activity
      get    ":type/:id/edit" => "activities#edit",  as: :edit_activity
      put    ":type/:id"      => "activities#update"
      patch  ":type/:id"      => "activities#update"
      delete ":type/:id"      => "activities#destroy"
    end
  end

  root to: "events#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :administrators, inverse_of: :event, dependent: :destroy,
    autosave: true
  has_many :packages, inverse_of: :event, dependent: :destroy, autosave: true
  has_many :registrations, inverse_of: :event, dependent: :destroy
  has_many :activity_types, inverse_of: :event, dependent: :destroy,
    autosave: true

  before_validation :generate_slug, if: :name?
  before_validation :update_times

  validates :starts_on, :ends_on, :starts_at, :stops_at, :time_zone,
    presence: { allow_blank: false }
  validates :name, :slug, presence: { allow_blank: false }
  validates :slug, uniqueness: { case_sensitive: false }
  validates_with DateValidator, if: [:starts_on?, :ends_on?]

  def to_param
    slug
  end

  def self.administered_by(user)
    joins(:administrators).where(administrators: { user_id: user.id })
  end

  private

  def generate_slug
    self.slug = name.to_url if slug.blank?
  end

  def update_times
    Time.use_zone(time_zone) do
      self.starts_at = starts_on.beginning_of_day if starts_on?
      self.stops_at = ends_on.beginning_of_day + 1.day if ends_on?
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_event, only: [:show, :edit, :update, :destroy]

  wrap_parameters :event, include: [:name, :packages, :activity_types]

  require_power_check
  power :events, as: :events

  def index
  end

  def show
  end

  def new
    @event = events.new
    current_power.creatable_event!(@event)
  end

  def create
    create_or_update_event(CreateEvent.new(current_user, event_params))
  end

  def edit
    current_power.updatable_event!(@event)
  end

  def update
    current_power.updatable_event!(@event)
    create_or_update_event(UpdateEvent.new(@event, event_params))
  end

  private

  def event_params
    params.require(:event)
      .permit(*current_power.assignable_event_fields, package_limit_fields)
  end

  def package_limit_fields
    packages = params[:event] && params[:event][:packages]
    return {} unless packages.present?

    activity_type_ids = packages.values.inject([]) do |ids, pkg|
      ids | pkg[:limits].keys
    end

    { packages: [:id, :name, :position, { limits: activity_type_ids }] }
  end

  def load_event
    @event ||= events.find_by!(slug: params[:id])
  end

  def create_or_update_event(service)
    service.call
    respond_with_success(service)
  rescue ActiveRecord::RecordInvalid
    respond_with_failure(service)
  end

  def respond_with_success(service)
    respond_to do |format|
      format.html { redirect_to(edit_event_path(service.event)) }
      format.json { render(json: service.event) }
    end
  end

  def respond_with_failure(service)
    respond_to do |format|
      @event = service.event

      format.html { render(action: @event.new_record? ? "new" : "edit") }
      format.json { render(json: @event.errors, status: :unprocessable_entity) }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def package_editor(event)
    packages = ActiveModel::SerializableResource.new(event.packages)
    activity_types = ActiveModel::SerializableResource.new(event.activity_types)

    mithril_component(
      "App.Components.PackageEditor",
      {
        packages: packages.serializable_hash,
        activity_types: activity_types.serializable_hash
      },
      class: "package-editor"
    )
  end
end

app/views/events/_form.html.haml
= form_for @event do |form|
  = form.label(:name)
  = form.text_field(:name)
  = inline_errors_for(@event, :name)

  = form.label(:slug)
  = form.text_field(:slug)
  = inline_errors_for(@event, :slug)

  = form.label(:starts_on)
  = form.date_field(:starts_on)
  = inline_errors_for(@event, :starts_on)

  = form.label(:ends_on)
  = form.date_field(:ends_on)
  = inline_errors_for(@event, :ends_on)

  = save_button(form)

app/views/events/edit.html.haml
- tabs do |strip|
  = strip.tab(t(".tabs.settings"), "settings") do
    = render "form"
  = strip.tab(t(".tabs.packages"), "packages") do
    = form_for @event do |form|
      = package_editor(@event)

app/views/events/index.html.haml
%h1 Home

app/views/events/new.html.haml
= form_for @event do |form|
  = @event.errors.inspect

  = form.label(:name)
  = form.text_field(:name)
  = inline_errors_for(@event, :name)

  = form.label(:slug)
  = form.text_field(:slug)
  = inline_errors_for(@event, :slug)

  = form.label(:starts_on)
  = form.date_field(:starts_on)
  = inline_errors_for(@event, :starts_on)

  = form.label(:ends_on)
  = form.date_field(:ends_on)
  = inline_errors_for(@event, :ends_on)

  = button_tag t(".create"), type: :submit

app/views/events/show.html.haml
%h1= @event.name

= link_to(t(".register"), event_registration_path(@event))